version: "3"
services:
    movies-api:
        build: .
        ports:
            - "3015:3015"
        restart: on-failure
        environment:
          - NODE_ENV=production
        depends_on:
            - mongodb
        links:
            - mongodb
    mongodb:
        image: "mongo"
        ports:
          - "27017:27017"